spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      uri: mongodb://test:123456@localhost:27017/data
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: data